version: '3'
services:
  herotrip:
    build: .
    environment: 
      - NODE_ENV=production
      - DATABASE_HOST=mysql
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=herotrip
      - DATABASE_DATABASE=herotrip
      - REDIS_HOST=redis
      - REDIS_PORT=6379 
    ports:
      - "3100:3100"
    depends_on: 
      - mysql
      - redis
  mysql:
    image: mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=herotrip
      - MYSQL_DATABASE=herotrip
    ports:
      - "3306:3306"
  redis:
    image: redis
    ports:
      - "6379:6379"